# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prometheus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10prometheus.proto\x12\nprometheus\":\n\x0cWriteRequest\x12*\n\ntimeseries\x18\x01 \x03(\x0b\x32\x16.prometheus.TimeSeries\"1\n\x0bReadRequest\x12\"\n\x07queries\x18\x01 \x03(\x0b\x32\x11.prometheus.Query\"8\n\x0cReadResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.prometheus.QueryResult\"\x8f\x01\n\x05Query\x12\x1a\n\x12start_timestamp_ms\x18\x01 \x01(\x03\x12\x18\n\x10\x65nd_timestamp_ms\x18\x02 \x01(\x03\x12*\n\x08matchers\x18\x03 \x03(\x0b\x32\x18.prometheus.LabelMatcher\x12$\n\x05hints\x18\x04 \x01(\x0b\x32\x15.prometheus.ReadHints\"9\n\x0bQueryResult\x12*\n\ntimeseries\x18\x01 \x03(\x0b\x32\x16.prometheus.TimeSeries\"*\n\x06Sample\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"T\n\nTimeSeries\x12!\n\x06labels\x18\x01 \x03(\x0b\x32\x11.prometheus.Label\x12#\n\x07samples\x18\x02 \x03(\x0b\x32\x12.prometheus.Sample\"$\n\x05Label\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"+\n\x06Labels\x12!\n\x06labels\x18\x01 \x03(\x0b\x32\x11.prometheus.Label\"\x82\x01\n\x0cLabelMatcher\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.prometheus.LabelMatcher.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"(\n\x04Type\x12\x06\n\x02\x45Q\x10\x00\x12\x07\n\x03NEQ\x10\x01\x12\x06\n\x02RE\x10\x02\x12\x07\n\x03NRE\x10\x03\"L\n\tReadHints\x12\x0f\n\x07step_ms\x18\x01 \x01(\x03\x12\x0c\n\x04\x66unc\x18\x02 \x01(\t\x12\x10\n\x08start_ms\x18\x03 \x01(\x03\x12\x0e\n\x06\x65nd_ms\x18\x04 \x01(\x03\x42\x08Z\x06prompbb\x06proto3')



_WRITEREQUEST = DESCRIPTOR.message_types_by_name['WriteRequest']
_READREQUEST = DESCRIPTOR.message_types_by_name['ReadRequest']
_READRESPONSE = DESCRIPTOR.message_types_by_name['ReadResponse']
_QUERY = DESCRIPTOR.message_types_by_name['Query']
_QUERYRESULT = DESCRIPTOR.message_types_by_name['QueryResult']
_SAMPLE = DESCRIPTOR.message_types_by_name['Sample']
_TIMESERIES = DESCRIPTOR.message_types_by_name['TimeSeries']
_LABEL = DESCRIPTOR.message_types_by_name['Label']
_LABELS = DESCRIPTOR.message_types_by_name['Labels']
_LABELMATCHER = DESCRIPTOR.message_types_by_name['LabelMatcher']
_READHINTS = DESCRIPTOR.message_types_by_name['ReadHints']
_LABELMATCHER_TYPE = _LABELMATCHER.enum_types_by_name['Type']
WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.Query)
  })
_sym_db.RegisterMessage(Query)

QueryResult = _reflection.GeneratedProtocolMessageType('QueryResult', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESULT,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.QueryResult)
  })
_sym_db.RegisterMessage(QueryResult)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.Sample)
  })
_sym_db.RegisterMessage(Sample)

TimeSeries = _reflection.GeneratedProtocolMessageType('TimeSeries', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIES,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.TimeSeries)
  })
_sym_db.RegisterMessage(TimeSeries)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), {
  'DESCRIPTOR' : _LABEL,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.Label)
  })
_sym_db.RegisterMessage(Label)

Labels = _reflection.GeneratedProtocolMessageType('Labels', (_message.Message,), {
  'DESCRIPTOR' : _LABELS,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.Labels)
  })
_sym_db.RegisterMessage(Labels)

LabelMatcher = _reflection.GeneratedProtocolMessageType('LabelMatcher', (_message.Message,), {
  'DESCRIPTOR' : _LABELMATCHER,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.LabelMatcher)
  })
_sym_db.RegisterMessage(LabelMatcher)

ReadHints = _reflection.GeneratedProtocolMessageType('ReadHints', (_message.Message,), {
  'DESCRIPTOR' : _READHINTS,
  '__module__' : 'prometheus_pb2'
  # @@protoc_insertion_point(class_scope:prometheus.ReadHints)
  })
_sym_db.RegisterMessage(ReadHints)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006prompb'
  _WRITEREQUEST._serialized_start=32
  _WRITEREQUEST._serialized_end=90
  _READREQUEST._serialized_start=92
  _READREQUEST._serialized_end=141
  _READRESPONSE._serialized_start=143
  _READRESPONSE._serialized_end=199
  _QUERY._serialized_start=202
  _QUERY._serialized_end=345
  _QUERYRESULT._serialized_start=347
  _QUERYRESULT._serialized_end=404
  _SAMPLE._serialized_start=406
  _SAMPLE._serialized_end=448
  _TIMESERIES._serialized_start=450
  _TIMESERIES._serialized_end=534
  _LABEL._serialized_start=536
  _LABEL._serialized_end=572
  _LABELS._serialized_start=574
  _LABELS._serialized_end=617
  _LABELMATCHER._serialized_start=620
  _LABELMATCHER._serialized_end=750
  _LABELMATCHER_TYPE._serialized_start=710
  _LABELMATCHER_TYPE._serialized_end=750
  _READHINTS._serialized_start=752
  _READHINTS._serialized_end=828
# @@protoc_insertion_point(module_scope)
